ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'VIEWER';
ALTER TABLE "Organization" ALTER COLUMN "defaultMemberRole" SET DEFAULT 'VIEWER';
ALTER TABLE "Invitation" ALTER COLUMN "role" SET DEFAULT 'VIEWER';

UPDATE "User"
SET "role" = CASE
  WHEN UPPER(COALESCE("role", '')) IN ('SUPER_ADMIN') THEN 'SUPER_ADMIN'
  WHEN UPPER(COALESCE("role", '')) IN ('PLATFORM_OWNER', 'PLATFORM_SUPPORT') THEN 'SUPER_ADMIN'
  WHEN UPPER(COALESCE("role", '')) IN ('OWNER') THEN 'OWNER'
  WHEN UPPER(COALESCE("role", '')) IN ('ADMIN', 'DEPARTMENT_MANAGER') THEN 'ADMIN'
  WHEN UPPER(COALESCE("role", '')) IN ('TECHNICIAN', 'OPERATOR') THEN 'TECHNICIAN'
  ELSE 'VIEWER'
END;

UPDATE "Organization"
SET "defaultMemberRole" = CASE
  WHEN UPPER(COALESCE("defaultMemberRole", '')) IN ('SUPER_ADMIN') THEN 'SUPER_ADMIN'
  WHEN UPPER(COALESCE("defaultMemberRole", '')) IN ('PLATFORM_OWNER', 'PLATFORM_SUPPORT') THEN 'SUPER_ADMIN'
  WHEN UPPER(COALESCE("defaultMemberRole", '')) IN ('OWNER') THEN 'OWNER'
  WHEN UPPER(COALESCE("defaultMemberRole", '')) IN ('ADMIN', 'DEPARTMENT_MANAGER') THEN 'ADMIN'
  WHEN UPPER(COALESCE("defaultMemberRole", '')) IN ('TECHNICIAN', 'OPERATOR') THEN 'TECHNICIAN'
  ELSE 'VIEWER'
END;

UPDATE "Invitation"
SET "role" = CASE
  WHEN UPPER(COALESCE("role", '')) IN ('SUPER_ADMIN') THEN 'SUPER_ADMIN'
  WHEN UPPER(COALESCE("role", '')) IN ('PLATFORM_OWNER', 'PLATFORM_SUPPORT') THEN 'SUPER_ADMIN'
  WHEN UPPER(COALESCE("role", '')) IN ('OWNER') THEN 'OWNER'
  WHEN UPPER(COALESCE("role", '')) IN ('ADMIN', 'DEPARTMENT_MANAGER') THEN 'ADMIN'
  WHEN UPPER(COALESCE("role", '')) IN ('TECHNICIAN', 'OPERATOR') THEN 'TECHNICIAN'
  ELSE 'VIEWER'
END;
